version: '3.2'

services:
  db:
    container_name: database 
    image: postgres:13.3
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD

    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql
    
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py

    volumes:
      - .:/src
      - type: volume
        source: users_files
        target: /scr/users_files
    ports:
      - 8001:8001
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    # Бот стартует после запуска базы
    depends_on:
      - db
      - django
      
 
  django:
    container_name: djangoproject
    build:
      context: .
    command: python django_app.py runserver 0.0.0.0:8000 --noreload
    ports:
      - 8000:8000
    networks:
      - botnet
    restart: always

    volumes:
      - .:/src
      - type: volume
        source: users_files
        target: /scr/users_files

    env_file:
      - ".env"
    # Бот стартует после запуска базы
    depends_on:
      - db
volumes:
  users_files:
    external: true
networks:
  botnet:
    driver: bridge 