version: '3.1'

services:
  db:
    container_name: database 
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD

    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql
  
  #tgbot:
  #  container_name: bot
  #  build:
  #    context: .
  #  command: python app.py
  #  networks:
  #    - botnet
  #  restart: always
  #  env_file:
  #    - ".env"
  #  volumes:
  #    - .:/src
  #  depends_on:
  #    - db


networks:
  botnet:
    driver: bridge 