# Generated by Django 3.2 on 2022-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID Пользователя Телеграм')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Пользователя')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username Телеграм')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_product', models.CharField(max_length=100, verbose_name='Имя заказа')),
                ('type_request', models.CharField(choices=[('3D', '3д печать'), ('laser', 'Лазерная резка')], max_length=10, verbose_name='Тип Запроса')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('promptness', models.IntegerField(verbose_name='Степень срочности')),
                ('comment', models.CharField(max_length=500, null=True, verbose_name='Комментарий')),
                ('readiness', models.IntegerField(choices=[(1, '?'), (2, 'принят'), (3, 'в работе'), (4, 'готов'), (5, 'вручен')], verbose_name='Готовность')),
                ('path_to_file', models.CharField(max_length=100, null=True, unique=True, verbose_name='Путь до файла')),
                ('name_user', models.ForeignKey(on_delete=models.SET(0), to='usersmanage.user', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
